addSbtPlugin("com.dwijnand"      % "sbt-dynver"          % "3.0.0")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"        % "1.4.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.0.0")
addSbtPlugin("io.get-coursier"   % "sbt-coursier"        % "1.0.1")
addSbtPlugin("org.scala-js"      % "sbt-scalajs"         % "0.6.22")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalajs-bundler" % "0.12.0")
